extends SceneTree

func _init() -> void:
    call_deferred("run")

func until(check: Callable, seconds := 12.0) -> void:
    var elapsed := 0.0
    while not check.call() and elapsed < seconds:
        await create_timer(.1).timeout
        elapsed += .1
    assert(check.call(),"online condition timed out")

func walk(session, target: Vector2) -> void:
    var elapsed := 0.0
    while Vector2(session.player.position.x,session.player.position.z).distance_to(target) > .3 and elapsed < 12:
        session.hud.stick.axis = (target-Vector2(session.player.position.x,session.player.position.z)).normalized()
        await create_timer(.1).timeout
        elapsed += .1
    session.hud.stick.release()
    assert(elapsed < 12,"navigation timed out")
    await create_timer(.5).timeout

func run() -> void:
    var api = root.get_node("ApiClient")
    var app = load("res://scenes/app/bootstrap.tscn").instantiate()
    root.add_child(app)
    await create_timer(.2).timeout
    app.server_url = OS.get_environment("VT_TEST_API_URL")
    app.email.text = "godot@example.test"
    app.password.text = "development-only-password"
    app.display_name.text = "Godot tester"
    await app.authenticate(true)
    assert(not api.access_token.is_empty(),"registration failed")
    await app.create_character("Reef Tester",0,0,0)
    assert(not app.selected_character.is_empty(),"creation failed")
    await app.enter_world()
    var session = app.session
    assert(session != null,"world did not open")
    await until(func(): return session.connection.connected and session.remotes.size() == 1)
    await walk(session,Vector2(-4,-3))
    await session.open_dialogue()
    assert(session.dialogue.node == "greeting","dialogue did not come from server")
    await session.choose_dialogue("ask_well")
    assert(session.dialogue.node == "explain_well","branch traversal failed")
    await session.choose_dialogue("offer_help")
    assert(session.character.quest_state.has("lantern_well_first_light"),"quest offer failed")
    await walk(session,Vector2(0,-3))
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(10,-10))
    await session.start_encounter()
    assert(session.character.encounter.state == "active","server proximity rejected encounter")
    for beat in 4:
        session.cast("glimmer_spark")
        await until(func(): return not session.busy)
    assert(session.character.encounter.state == "victory","combat did not resolve")
    assert(session.character.wallet.shell_chits == 14,"reward mismatch")
    var identity = session.character.id
    session.hud.close_panel()
    session.connection.socket.close()
    await until(func(): return not session.connection.connected)
    await until(func(): return session.connection.connected)
    var saved = await api.get_json("/world/characters/" + identity)
    assert(saved.wallet.shell_chits == 14,"reconnect changed reward")
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert(session.dialogue.node == "after_lurker","progress-aware dialogue failed")
    await session.choose_dialogue("follow_note")
    await walk(session,Vector2(-8,-12))
    await session.inspect_landmark("sunthread_reeds")
    session.hud.close_panel()
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(16,-17))
    await session.inspect_landmark("saltglass_cistern")
    session.hud.close_panel()
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert(session.dialogue.node == "answer_found","Mara did not react to discoveries")
    assert(session.character.quest_state.an_answer_in_the_reeds.completed,"follow-up unfinished")
    assert(session.character.wallet.shell_chits == 19,"follow-up reward mismatch")
    await session.open_dialogue()
    assert(session.character.wallet.shell_chits == 19,"repeated talk duplicated reward")
    var final_saved = await api.get_json("/world/characters/" + identity)
    assert(final_saved.experience == 140,"follow-up was not persisted")
    await session.choose_dialogue("study_reading_the_afterlight")
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(16,-17))
    await session.inspect_landmark("saltglass_cistern")
    session.hud.close_panel()
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert("beacon_trace" in session.character.known_spells)
    assert("beacon_trace" not in session.character.folio)
    await session.choose_dialogue("study_what_the_reeds_hold")
    await walk(session,Vector2(-8,-12))
    await session.inspect_landmark("sunthread_reeds")
    session.hud.close_panel()
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert("reed_aegis" in session.character.known_spells)
    await session.choose_dialogue("study_a_measured_release")
    await session.show_folio()
    assert(session.folio_panel.choices.size() == 5)
    assert(not session.folio_panel.choices.has("seam_lance"))
    session.folio_panel.choices.beacon_trace.pressed.emit()
    session.folio_panel.choices.reed_aegis.pressed.emit()
    session.folio_panel.choices.root_snare.pressed.emit()
    session.folio_panel.save_button.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.folio.size() == 4 and session.character.folio_revision == 1)
    session.hud.close_panel()
    session.connection.socket.close()
    await until(func(): return not session.connection.connected)
    await until(func(): return session.connection.connected)
    await session.show_folio()
    assert(session.folio_panel.selected == session.character.folio)
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(10,-10))
    await session.start_encounter()
    assert(not session.character.encounter.spells.has("root_snare"))
    var rejected = await api.post_json("/world/characters/%s/encounters/actions" % identity,{"encounter_id":session.character.encounter.id,"action":"root_snare","expected_round":1},"unprepared-spell")
    assert(rejected.is_empty(),"server accepted learned-but-unprepared spell")
    for action in ["beacon_trace","reed_aegis","gather","glimmer_spark","reed_aegis","tide_mend","glimmer_spark","reed_aegis","gather","glimmer_spark","reed_aegis","tide_mend","glimmer_spark"]:
        session.cast(action)
        await until(func(): return not session.busy)
    assert(session.character.encounter.state == "victory")
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert(session.dialogue.node == "lance_learned")
    assert(session.character.known_spells.size() == 6)
    assert("seam_lance" not in session.character.folio)
    await session.open_dialogue()
    assert(session.character.known_spells.size() == 6 and session.character.wallet.shell_chits == 21)
    await session.show_folio()
    session.folio_panel.choices.seam_lance.pressed.emit()
    session.folio_panel.save_button.pressed.emit()
    await until(func(): return not session.busy)
    var prepared_saved = await api.get_json("/world/characters/" + identity)
    assert("seam_lance" in prepared_saved.folio and prepared_saved.folio_revision == 2)
    assert(prepared_saved.experience == 165)
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(10,-10))
    await session.start_encounter()
    session.cast("gather")
    await until(func(): return not session.busy)
    session.cast("seam_lance")
    await until(func(): return not session.busy)
    assert(session.character.encounter.enemy_vigor == 17,"earned/prepared lance was not playable")
    app.return_to_gateway()
    await api.post_json("/auth/logout",{})
    app.queue_free()
    await process_frame
    print("GODOT_ONLINE_PASS: account, creation, two-player presence, movement, branching dialogue, quest, combat, rewards, reconnect, ordered Mara investigation, once-only rewards, three earned spells, touch folio selection, persistence, rejected unprepared cast, earned Seam Lance combat")
    quit()
