extends SceneTree

func _init() -> void:
    call_deferred("run")

func until(check: Callable, seconds := 12.0) -> void:
    var elapsed := 0.0
    while not check.call() and elapsed < seconds:
        await create_timer(.1).timeout
        elapsed += .1
    assert(check.call(),"online condition timed out")

func walk(session, target: Vector2) -> void:
    var elapsed := 0.0
    while Vector2(session.player.position.x,session.player.position.z).distance_to(target) > .3 and elapsed < 12:
        session.hud.stick.axis = (target-Vector2(session.player.position.x,session.player.position.z)).normalized()
        await create_timer(.1).timeout
        elapsed += .1
    session.hud.stick.release()
    assert(elapsed < 12,"navigation timed out")
    await create_timer(.5).timeout

func run() -> void:
    var api = root.get_node("ApiClient")
    var app = load("res://scenes/app/bootstrap.tscn").instantiate()
    root.add_child(app)
    await create_timer(.2).timeout
    app.server_url = OS.get_environment("VT_TEST_API_URL")
    app.email.text = "godot@example.test"
    app.password.text = "development-only-password"
    app.display_name.text = "Godot tester"
    await app.authenticate(true)
    assert(not api.access_token.is_empty(),"registration failed")
    await app.create_character("Reef Tester",0,0,0)
    assert(not app.selected_character.is_empty(),"creation failed")
    await app.enter_world()
    var session = app.session
    assert(session != null,"world did not open")
    await until(func(): return session.connection.connected and session.remotes.size() == 1)
    await walk(session,Vector2(-4,-3))
    await session.open_dialogue()
    assert(session.dialogue.node == "greeting","dialogue did not come from server")
    await session.choose_dialogue("ask_well")
    assert(session.dialogue.node == "explain_well","branch traversal failed")
    await session.choose_dialogue("offer_help")
    assert(session.character.quest_state.has("lantern_well_first_light"),"quest offer failed")
    await walk(session,Vector2(0,-3))
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(10,-10))
    await session.start_encounter()
    assert(session.character.encounter.state == "active","server proximity rejected encounter")
    for beat in 4:
        session.short_spell_effects = beat == 1
        session.cast("glimmer_spark")
        await until(func(): return not session.busy)
        assert(session.hud.visible and session.camera.camera.current,"Cast presentation did not restore navigation")
    session.short_spell_effects = false
    assert(session.character.encounter.state == "victory","combat did not resolve")
    assert(session.character.wallet.shell_chits == 14,"reward mismatch")
    var identity = session.character.id
    session.hud.close_panel()
    session.connection.socket.close()
    await until(func(): return not session.connection.connected)
    await until(func(): return session.connection.connected)
    var saved = await api.get_json("/world/characters/" + identity)
    assert(saved.wallet.shell_chits == 14,"reconnect changed reward")
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert(session.dialogue.node == "after_lurker","progress-aware dialogue failed")
    await session.choose_dialogue("follow_note")
    await walk(session,Vector2(-8,-12))
    await session.inspect_landmark("sunthread_reeds")
    session.hud.close_panel()
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(16,-17))
    await session.inspect_landmark("saltglass_cistern")
    session.hud.close_panel()
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert(session.dialogue.node == "answer_found","Mara did not react to discoveries")
    assert(session.character.quest_state.an_answer_in_the_reeds.completed,"follow-up unfinished")
    assert(session.character.wallet.shell_chits == 19,"follow-up reward mismatch")
    await session.open_dialogue()
    assert(session.character.wallet.shell_chits == 19,"repeated talk duplicated reward")
    var final_saved = await api.get_json("/world/characters/" + identity)
    assert(final_saved.experience == 140,"follow-up was not persisted")
    await session.choose_dialogue("study_reading_the_afterlight")
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(16,-17))
    await session.inspect_landmark("saltglass_cistern")
    session.hud.close_panel()
    await walk(session,Vector2(0,-14))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert("beacon_trace" in session.character.known_spells)
    assert("beacon_trace" not in session.character.folio)
    await session.choose_dialogue("study_what_the_reeds_hold")
    await walk(session,Vector2(-8,-12))
    await session.inspect_landmark("sunthread_reeds")
    session.hud.close_panel()
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert("reed_aegis" in session.character.known_spells)
    await session.choose_dialogue("study_a_measured_release")
    await session.show_folio()
    assert(session.folio_panel.choices.size() == 5)
    assert(not session.folio_panel.choices.has("seam_lance"))
    session.folio_panel.choices.beacon_trace.pressed.emit()
    session.folio_panel.choices.reed_aegis.pressed.emit()
    session.folio_panel.choices.root_snare.pressed.emit()
    session.folio_panel.save_button.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.folio.size() == 4 and session.character.folio_revision == 1)
    session.hud.close_panel()
    session.connection.socket.close()
    await until(func(): return not session.connection.connected)
    await until(func(): return session.connection.connected)
    await session.show_folio()
    assert(session.folio_panel.selected == session.character.folio)
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(10,-10))
    await session.start_encounter()
    assert(not session.character.encounter.spells.has("root_snare"))
    var rejected = await api.post_json("/world/characters/%s/encounters/actions" % identity,{"encounter_id":session.character.encounter.id,"action":"root_snare","expected_round":1},"unprepared-spell")
    assert(rejected.is_empty(),"server accepted learned-but-unprepared spell")
    for action in ["beacon_trace","reed_aegis","gather","glimmer_spark","reed_aegis","tide_mend","glimmer_spark","reed_aegis","gather","glimmer_spark","reed_aegis","tide_mend","glimmer_spark"]:
        session.cast(action)
        await until(func(): return not session.busy)
    assert(session.character.encounter.state == "victory")
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(-4,-4))
    await session.open_dialogue()
    assert(session.dialogue.node == "lance_learned")
    assert(session.character.known_spells.size() == 6)
    assert("seam_lance" not in session.character.folio)
    await session.open_dialogue()
    assert(session.character.known_spells.size() == 6 and session.character.wallet.shell_chits == 21)
    await session.show_folio()
    session.folio_panel.choices.seam_lance.pressed.emit()
    session.folio_panel.save_button.pressed.emit()
    await until(func(): return not session.busy)
    var prepared_saved = await api.get_json("/world/characters/" + identity)
    assert("seam_lance" in prepared_saved.folio and prepared_saved.folio_revision == 2)
    assert(prepared_saved.experience == 165)
    # M1.3 spends genuinely earned currency through the same UI actions as touch.
    await session.show_vendor()
    assert(session.commerce_view.shop.listings[0].price == 12)
    assert(session.commerce_view.shop.listings[0].guard_delta == 1)
    assert(not session.commerce_panel.buy_buttons.buy_sunthread_bandage.disabled)
    session.commerce_panel.buy_buttons.buy_lanternkeeper_vest.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.wallet.shell_chits == 9 and session.character.inventory.lanternkeeper_vest == 1)
    assert(session.character.equipment.is_empty())
    session.commerce_panel.equip_buttons.lanternkeeper_vest.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.equipment.chest == "lanternkeeper_vest")
    assert(session.commerce_view.stats.guard == 1)
    assert(session.commerce_panel.buy_buttons.buy_lanternkeeper_vest.disabled)
    await session.show_inventory()
    session.commerce_panel.unequip_button.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.equipment.is_empty() and session.commerce_view.stats.guard == 0)
    session.commerce_panel.equip_buttons.lanternkeeper_vest.pressed.emit()
    await until(func(): return not session.busy)
    session.hud.close_panel()
    session.connection.socket.close()
    await until(func(): return not session.connection.connected)
    await until(func(): return session.connection.connected)
    await session.show_inventory()
    assert(session.character.equipment.chest == "lanternkeeper_vest")
    assert(session.character.commerce_revision == 4 and session.character.wallet.shell_chits == 9)
    assert(session.character.appearance == prepared_saved.appearance)
    assert(session.character.folio == prepared_saved.folio)
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(10,-10))
    await session.start_encounter()
    assert(session.character.encounter.equipment_guard == 1)
    var before_guard = session.character.encounter.player_vigor
    session.cast("gather")
    await until(func(): return not session.busy)
    assert(session.character.encounter.player_vigor == before_guard - 3)
    session.cast("seam_lance")
    await until(func(): return not session.busy)
    assert(session.character.encounter.enemy_vigor == 17,"earned/prepared lance was not playable")
    for spell in ["gather","seam_lance","glimmer_spark"]:
        session.cast(spell)
        await until(func(): return not session.busy)
    assert(session.character.encounter.state == "victory")
    session.hud.close_panel()
    await walk(session,Vector2(0,-10))
    await walk(session,Vector2(-4,-4))
    await session.show_vendor()
    var supply_count = int(session.character.inventory.sunthread_bandage)
    var balance = int(session.character.wallet.shell_chits)
    session.commerce_panel.buy_buttons.buy_sunthread_bandage.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.wallet.shell_chits == balance-5)
    await session.show_inventory()
    var before_wrap = int(session.character.vigor)
    assert(before_wrap < 30 and not session.commerce_panel.use_buttons.sunthread_bandage.disabled)
    session.commerce_panel.use_buttons.sunthread_bandage.pressed.emit()
    await until(func(): return not session.busy)
    assert(session.character.vigor == mini(30,before_wrap+12))
    assert(session.character.inventory.sunthread_bandage == supply_count)
    var healed = int(session.character.vigor)
    session.connection.socket.close()
    await until(func(): return not session.connection.connected)
    await until(func(): return session.connection.connected)
    await session.show_inventory()
    assert(session.character.vigor == healed and session.character.commerce_revision == 6)
    # A stale use must preserve supplies and surface the server's actionable reason.
    session.pending_commerce = {"key":"online-stale-wrap","path":"items/use","payload":{"item_key":"sunthread_bandage","expected_revision":0}}
    await session.retry_commerce()
    assert("changed" in session.commerce_error.to_lower())
    assert(not session.pending_commerce.is_empty())
    await session.reload_commerce()
    assert(session.pending_commerce.is_empty())
    assert(session.character.vigor == healed and session.character.commerce_revision == 6)
    assert(session.character.inventory.sunthread_bandage == supply_count)
    print("GODOT_ITEM_USE_PASS: earned purchase, Bag use, capped healing, inventory and reconnect")
    app.return_to_gateway()
    await api.post_json("/auth/logout",{})
    app.queue_free()
    await process_frame
    print("GODOT_ONLINE_PASS: account, creation, two-player presence, movement, branching dialogue, quest, combat, rewards, reconnect, ordered Mara investigation, once-only rewards, three earned spells, folio selection, persistence, rejected unprepared cast, earned Seam Lance combat; vendor UI purchase with earned currency, comparison, equip/unequip/reconnect, Guard effect and preserved appearance/folio")
    quit()
